### ISSUE TITLE
Unable to bring up development environment on Windows

### ISSUE THREAD

**Issue by peter337** [wellcometrust/policytool#167]
Hi all - sorry my first contribution in so long is an issue!
I'm currently trying to run Wellcome Reach on the UKRI laptops (running Windows 10), which I'm certain I successfully did when I returned in March, but no longer seems to be working.

Running `make virtualenv` returns:
> D:\Users\XXX\Documents\Python Projects\policytool>make virtualenv
> 'make' is not recognized as an internal or external command,
> operable program or batch file.

(I'd also like to bring your attention to my horrendous username at UKRI)

Attempting to just run refparse.py returns:
> D:\Users\XXX\Documents\Python Projects\policytool\policytool\refparse>python refparse.py
> Traceback (most recent call last):
>   File "refparse.py", line 16, in <module>
>     from .utils import (FileManager,
> ModuleNotFoundError: No module named '\_\_main\_\_.utils'; '\_\_main\_\_' is not a package

Nick suggested raising an issue would be the best way to open a discussion on this, really appreciative for any suggestions 😄

**Comment by hblanks** [comment]
@peter337 - great to hear from you! Yes that's quite the username. (Hope it's OK I redacted it for you, though it does remain visble in the edit history...)

We definitely want to get a working Windows story in place for the tool. Getting that going means installing the set of dependencies under [README.md#dependencies](https://github.com/wellcometrust/policytool/#dependencies), plus one I failed to mention there because it's (outside Windows) ubiquitous: make (and probably GNU make, to be specific).

My thoughts to get things in order for you here are:

1. Install Windows Subsystem for Linux 2.0 with a recent Debian or Ubuntu distro on top, or
2. Install cygwin, either with or without admin privileges, and install make & the requisite Python bits from there.
3. Install Virtualbox, set up an Ubuntu virtual machine, and do all development from within it.

Can you send an email my way with a few times when you're free to chat through these?

**Comment by hblanks** [comment]
Closing as wontfix since Peter, our one Windows user, no longer works at UKRI on this project :-(
