### ISSUE TITLE
Add urls to scrape data

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#244]
As far as I am aware from looking at the things saved in reach-airflow, at the moment the only things saved about the policy documents are ['file_hash', 'sections', 'keywords', 'text'].

I'd say it is very important to save the urls either here or in a metadata JSON (in which year and title would also be useful), perhaps even for the alpha release. Otherwise the policy document data has no real-world link anymore.

**Comment by nsorros** [comment]
Indeed this is very important so @SamDepardieu and @hblanks can comment on the state of that.

**Comment by SamDepardieu** [comment]
For the time beeing, we are focusing on getting Reach to a fully functionnal state, meaning getting searchable indexed citations and a web api.
This progress can be followed on the Reach dev plan (see here: https://github.com/wellcometrust/datalabs/blob/master/docs/product/reach/development-plan.md)

There's no doubt that once this is done, adding more fields will be on the next features list, though

**Comment by nsorros** [comment]
I added a feature request for this and will mention to Dawn to prioritise after the release of Reach

**Comment by dd207** [comment]
Hi, thanks for raising Liz. 

It's essential that users can access the URLs to policy documents, otherwise Reach is pretty redundant for a large part of our intended audience.

This needs to be prioritised for the alpha release or we won't be able to test the full user journey. 

Happy to have a chat with @hblanks and whoever else on how this affects timings etc.

**Comment by lizgzil** [comment]
Just to note that this also means I am blocked doing the Uber/Reach comparison when the first round of final data is through. This is because url is the unique field I use to say whether an Uber policy doc is the same thing as a Reach policy doc.

**Comment by SamDepardieu** [comment]
As it is blocking, I'll try to deploy a quick workaround this morning/early this afternoon. Note that we may have to change that later.

**Comment by ivyleavedtoadflax** [comment]
I'm a bit late to this party, having the `url` in stored in the scraped json would be very useful to allow annotators to click on a link and see the original document. 

Also I see that the `provider` value is also missing. This was very useful for stratifying documents by provider, so that we don't only see `who_iris` documents.

**Comment by lizgzil** [comment]
I have inferred provider from the url in the past, but I know not all the urls are so obvious in where they came from. Perhaps a balance between not adding too much more data to this output, and still saving the urls, would be to create a dictionary of all the url stems for each provider?

**Comment by ivyleavedtoadflax** [comment]
Is there any chance that we could just keep the url and provider in the scraped json which includes the reference sections? I don't think adding the url and provider is going to make much of a difference to these files which are already hundreds of Mb in size.
