### ISSUE TITLE
Rewrite input arguments in the README for methods 3 and 4

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#67]
In the README I find that I need to change
`mkdir -p /tmp/parser-output/output_folder_name`
to 
`mkdir -p ./tmp/parser-output/output_folder_name`
for method 3 and
` --output-url "file:///tmp/parser-output/output_folder_name" \`
to
` --output-url "file://./tmp/parser-output/output_folder_name" \`
and
`num-workers None`
to
`num-workers 1`
in methods 3 and 4, in order to get the code to work. 

In the case of the `output-url` argument the original way works without errors, but no folder and output files are created.

**Comment by peter337** [comment]
Copying comments from issue #71 - sorry for the duplicate!

Came across a couple of errors when testing the code in the README.

1. Under method 3 and 4, using ```--num-workers None``` returns ```error: argument --num-workers: invalid int value: 'None'```.

I think this is because of create_argparser in refparse.py, which tries to coerce 'None' to 'int'.

2. Under method 4, running ```python parse_latest.py msf``` returns ```Output url should start with 'file://'```.

I think this is because of a combination of: the if statement in parse_latest.py requiring output_url to start with 'file://'; and the default for output_url in settings.py beginning with 'postgresql+psycopg2://'.

**Comment by nsorros** [comment]
@peter337 well said, can you submit a fix for these errors and update documentation if needed?

**Comment by hblanks** [comment]
@peter337  - just a quick ping on this. LMK if there's anything I can do to help.

**Comment by peter337** [comment]
@lizgzil @hblanks With the PR merged, the issues raised here should now be resolved. However, the code in the README still doesn't run without crashing, due to the issues in https://github.com/wellcometrust/policytool/issues/81, which requires requires changes to settings.py.
